Tried to clarify documentation a tiny bit
jgiannuzzi/docker-letsencrypt-manuale pull request #1
Opened 2016-12-16 20:20 UTC by krgo

2016-12-20 07:42 UTC, jgiannuzzi requested changes

2016-12-20 07:42 UTC, jgiannuzzi commented on README.md
> +Once that's done, you can finally get down to business. Run `docker run --rm -ti -v $PWD:/data jgiannuzzi/letsencrypt-manuale issue example.com www.example.com` to get your certificates for `example.
There is only one certificate created in this example.

Could you change the sentence accordingly?

2016-12-21 11:13 UTC, krgo commented
I misunderstood how it worked. Please consider this update.

2016-12-21 12:24 UTC, jgiannuzzi approved these changes

2016-12-21 12:25 UTC, merged